export const DATOS_CURIOSOS_INICIO: string[] = [
    'Se considera más fiel al origen latino decir "extravertido" que "extrovertido", ya que proviene de extra- (hacia afuera) y vertere (girar). Aun así, "extrovertido" es hoy ampliamente aceptado y más usado.',
    'La expresión correcta es "craso error". "Craso" significa grave o evidente, mientras que "graso error" es un error por confusión fonética sin base en el significado real de la palabra.',
    'El verbo "haber" cuando indica existencia es impersonal, por lo que siempre va en singular: se debe decir "hubo problemas" y no "hubieron problemas", incluso si el complemento está en plural.',
    '"Ojalá" proviene del árabe inshallah, que significa "si Dios quiere", reflejando la fuerte influencia árabe en el español durante la Edad Media.',
    'En contextos formales se prefiere "con base en" o "basado en", aunque "en base a" es un uso extendido en el habla cotidiana.',
    'El dequeísmo consiste en agregar innecesariamente la preposición "de", como en "pienso de que vendrá". El queísmo es el fenómeno opuesto: omitirla cuando sí corresponde, como en "estoy seguro que vendrá" en lugar de "de que".',
    '"Bizarro" originalmente significa valiente o generoso en español. Sin embargo, por influencia del inglés "bizarre", hoy también se acepta con el sentido de "extraño".',
    'La palabra "trabajo" podría estar relacionada con el latín tripalium, un instrumento de sujeción o castigo. Esta etimología sugiere una asociación histórica con el esfuerzo, la dificultad o el sufrimiento, aunque no implica que originalmente significara “tortura” en sentido literal.',
    'La palabra "chocolate" proviene del náhuatl "xocolātl" y llegó al español tras la conquista de América. Otras palabras de ese mismo origen son "tomate", "aguacate", "chile" y "cacao".',
    '"Literalmente" significa "de acuerdo con el sentido exacto de las palabras, sin interpretación figurada". Su uso como intensificador ("me morí literalmente de risa") es muy común, pero técnicamente impreciso.',
    '"Eventualmente" no significa "finalmente". En español se usa para indicar algo ocasional o circunstancial. La confusión con el inglés "eventually" ha llevado a un uso incorrecto en algunos contextos.',
    '"Chancho en piedra" proviene de "chancar en piedra", es decir, moler los ingredientes, y no tiene relación con el animal.',
    'Expresiones como "subir para arriba" o "bajar para abajo" son pleonasmos: redundancias que repiten una idea ya implícita en el verbo.',
    '"Álgido" proviene del latín algidus (“frío”), pero en el uso actual se emplea principalmente para referirse al momento más intenso o crítico de una situación, como en “el punto álgido del debate”.',
    '"Imprimido" e "impreso" son formas correctas del participio de "imprimir". "Impreso" se usa más como adjetivo, mientras que "imprimido" se emplea en tiempos compuestos.',
    'La letra "ñ" surgió en la Edad Media como una abreviación de la doble "n", y con el tiempo se consolidó como una letra propia del español.',
    '"Usted" proviene de la expresión de cortesía "vuestra merced", que con el tiempo se fue abreviando y transformando fonéticamente hasta llegar a su forma actual.',
    '"Cerca mío" es frecuente en el español de América, pero en registros formales se prefiere "cerca de mí".',
    'Formas como "dijistes", "fuistes" o "vinistes" son incorrectas, ya que los verbos en pretérito perfecto simple no llevan "s" en la segunda persona singular.',
    '"Presidente" es un sustantivo común en cuanto al género, por lo que puede usarse tanto para hombres como para mujeres, aunque "presidenta" también es válida.',
    '"Septiembre" y "setiembre" son ambas formas correctas, aunque la primera es la más utilizada.',
    '"Inflamable" y "flamable" significan lo mismo: que algo puede arder con facilidad.',
    '"Excepción" y "acepción" tienen significados distintos: la primera se refiere a algo que se aparta de la regla, y la segunda a un significado de una palabra.',
    '"Así mismo", "asimismo" y "a sí mismo" tienen significados distintos: equivalencia, adición y referencia reflexiva, respectivamente.',
    'Las mayúsculas deben llevar tilde cuando las reglas de acentuación lo exigen.',
    '"Óptimo" significa "el mejor posible dentro de una categoría", no simplemente "muy bueno".',
    '"Único" no admite grados: algo no puede ser "muy único" en sentido estricto.',
    '"El agua" utiliza artículo masculino por razones fonéticas, pero sigue siendo una palabra femenina. Por eso se dice "el agua helada", pero también "las aguas heladas".',
    'La palabra "salario" proviene del latín salarium, relacionada con la sal, y aludía a una asignación para adquirirla.',
    '"Madrugada" no tiene equivalente exacto en inglés: no existe una sola palabra en esa lengua para referirse a las horas entre medianoche y el amanecer.',
    '"Aplicar a un trabajo" es un calco del inglés y se considera poco adecuado en español formal; se prefiere "postular a un trabajo".',
    '"Pretender" significa "intentar" o "tener la intención de", no "fingir". La confusión con el inglés "pretend" ha llevado a un uso incorrecto en algunos contextos.',
    '"Constipado" en español se refiere a un resfriado leve, no a estreñimiento.',
    'El verbo “prever” se conjuga como “ver”, por lo que la forma correcta es “previó” y no “preveyó”.',
    '"Sendos" no significa "grandes", sino "uno para cada uno". Por ejemplo, "recibieron sendos premios" significa que cada uno recibió un premio. La forma singular "sendo" no forma parte del uso estándar.',
    '"Enervar" significa debilitar o quitar energía, no "poner nervioso", aunque este último uso es frecuente.',
    '"Esperar" en español abarca dos significados que en inglés requieren dos palabras distintas: "to wait" (aguardar) y "to hope" (tener esperanza). El contexto determina cuál es cuál.',
    '"Demás" y "de más" no significan lo mismo: el primero se refiere a otros, el segundo a exceso.',
    '"Sino" y "si no" cumplen funciones distintas: oposición y condición, respectivamente.',
    '"Aparte" y "a parte" no son equivalentes: el primero significa "además" o "separado", el segundo implica "una parte de".',
    '"Sobre todo" significa "principalmente", mientras que "sobretodo" es una prenda de vestir.',
    '"Vaya", "valla" y "baya" tienen significados distintos: forma verbal o interjección, cerca, y fruto, respectivamente.',
    '"Haya", "halla" y "allá" se diferencian en significado: verbo haber o árbol, verbo hallar, y lugar.',
    '"Luego" tradicionalmente significa "después", pero en algunos países se usa como "inmediatamente", lo que puede generar ambigüedad.',
    'El adverbio "medio" es invariable cuando equivale a "un poco": se dice "medio cansada", no "media cansada".',
    '"Quien" y "quienes" llevan tilde ("quién", "quiénes") solo en interrogativas o exclamativas, directas o indirectas.',
    '"Por qué", "porque", "porqué" y "por que" cumplen funciones distintas: interrogativo, causal, sustantivo y combinación preposición + relativo.',
    '"A ver" (ver) y "haber" (verbo auxiliar) no son intercambiables: "a ver qué pasa" vs "debe haber algo".',
    '"Hecho" (del verbo hacer) y "echo" (del verbo echar) se distinguen por su origen y significado, aunque suenen igual.',
    '"Hay", "ahí" y "ay" tienen significados distintos: existencia, lugar e interjección, respectivamente.',
    '"Sé" puede ser del verbo saber o ser; "se" es un pronombre, y no llevan el mismo acento ni función.',
    '"Aun" y "aún" no siempre son intercambiables: "aún" equivale a "todavía", mientras que "aun" puede significar "incluso".',
    'Las palabras extranjeras adaptadas al español deben seguir sus reglas ortográficas: "fútbol", "líder", "récord".',
    '"Currículum" tiene varias formas de plural aceptadas: "currículums" y "currícula".',
    '"Cualquiera" pierde la -a en masculino singular: "cualquier hombre", pero "cualquiera mujer".',
    '"Primer" y "tercer" son apócopes de "primero" y "tercero" antes de sustantivos masculinos singulares.',
    'Los días de la semana y los meses se escriben con minúscula en español ("lunes", "enero").',
    'Las siglas no llevan puntos ni plural con "s": se escribe "las ONG", no "las ONGs".',
    'Las palabras terminadas en -mente conservan la tilde del adjetivo original: "rápidamente", "fácilmente".',
    '"Le" puede funcionar como complemento indirecto incluso en plural ("le dije a ellos"), fenómeno conocido como leísmo de cortesía en algunos contextos.',
    '"Hubiera" y "hubiese" son formas equivalentes del pretérito imperfecto del subjuntivo.',
    '"Mismo" en frases como "lo hice yo mismo" es correcto, pero su abuso como muletilla ("el mismo documento") se considera poco recomendable.',
    '"Que" puede ser conjunción o pronombre relativo; solo lleva tilde cuando es interrogativo o exclamativo.',
    '"Donde", "cuando" y "como" llevan tilde ("dónde", "cuándo", "cómo") en preguntas o énfasis.',
    'El verbo "caber" en pretérito es irregular: "cupe", "cupiste", "cupo".',
    'El verbo "andar" en pretérito también es irregular: "anduve", "anduviste", "anduvo".',
    '"Habían dicho" es correcto cuando "haber" es auxiliar, pero "habían personas" es incorrecto por ser impersonal.',
    '"Entre tú y yo" es correcto; "entre tú y mí" es incorrecto.',
    '"Detrás mío" es común en América, pero en registros formales se prefiere "detrás de mí".',
    '"Peor" y "mejor" son comparativos irregulares y no se combinan con "más": no se dice "más mejor".',
    '"Muy" modifica adjetivos o adverbios ("muy alto"), mientras que "mucho" modifica sustantivos o verbos ("mucho trabajo", "trabaja mucho").',
    '"Súper" como prefijo se escribe junto: "supermercado", pero separado cuando es adverbio coloquial: "súper bueno".',
    '"Ambos dos" es redundante, ya que "ambos" ya implica dualidad.',
    'El español tiene signos de apertura de interrogación y exclamación ("¿", "¡"), únicos entre las lenguas principales del mundo.',
    '"Más" lleva tilde cuando indica cantidad o comparación ("quiero más", "es más alto"), mientras que "mas" sin tilde es una conjunción equivalente a "pero", hoy poco usada ("quiso ir, mas no pudo").',
    '"Asumir" significa aceptar o hacerse cargo de algo ("asumió el cargo"), no simplemente "suponer". Aunque este último uso es frecuente por influencia del inglés "assume", en contextos formales se prefiere "suponer".',
    'El verbo "abolir" es defectivo: no se usa en todas sus formas, por lo que expresiones como "yo abolo" o "tú aboles" no se consideran correctas en el uso estándar.',
    '"Alguno" se apocopa a "algún" solo en masculino singular ("algún día"), pero no en femenino ("alguna vez").',
    '"Ninguno" también se apocopa: "ningún problema", pero "ninguna duda".',
    '"Buen" es la forma apocopada de "bueno" antes de sustantivo masculino singular ("buen día"), pero no se usa en femenino ni en plural.',
    '"Mañana" puede significar tanto el día siguiente como la parte inicial del día; el contexto determina el sentido.',
    '"Igual" se usa coloquialmente como muletilla ("igual voy"), pero en sentido estricto significa "de la misma manera" o "idéntico".',
    '"Recién" en varios países de América se usa como marcador de pasado inmediato ("recién llegué"), mientras que en español estándar se prefiere "acabo de llegar".',
    '"Nomás" es una contracción de "no más", válida en el uso coloquial; en registros formales se prefiere escribirlo separado.',
    'La doble negación es correcta en español: "no vi a nadie" es gramatical y refuerza la negación.',
    '"Aunque" puede expresar contraste ("aunque llueva, iré") o una situación hipotética ("aunque lloviera, iría"), según el modo verbal.',
    '"Cancha" proviene del quechua "kancha", que significaba espacio abierto o recinto. Es uno de los muchos aportes de las lenguas indígenas al español de América.',
    '"Quedar" puede significar "permanecer" ("quedó en casa") o "acordar" ("quedamos en vernos").',
    'El español tiene más de 480 millones de hablantes nativos, lo que lo convierte en la segunda lengua con más hablantes maternos del mundo, por delante del inglés.',
    '"Quien" puede funcionar como pronombre relativo sin antecedente explícito: "quien llegue primero gana".',
    '"Cuyo" indica posesión y concuerda en género y número con lo poseído, no con el poseedor. Es una palabra que casi ha desaparecido del habla cotidiana, pero que se mantiene en la escritura formal.',
    '"Acertar" no proviene de "cierto" (verdadero), sino del latín "ad-certare" (dirigirse hacia un blanco). Por eso "acertar" implica dar en el objetivo, no solo tener razón.',
    'El uso de "vos" como pronombre de segunda persona singular, frecuente en Argentina, Uruguay y parte de Centroamérica, es un arcaísmo medieval que desapareció del español europeo pero sobrevivió en América.',
    'Hasta 2010, "ch" y "ll" se consideraban letras del abecedario. Hoy se clasifican como dígrafos, aunque siguen sonando como unidades en muchos contextos.',
    'La Real Academia registra formas como "almóndiga" y "toballa" como variantes populares o vulgares: existen en el diccionario, pero no se recomiendan en la norma culta.',
    '"Murciégalo" no es una invención moderna: es una variante histórica de "murciélago" que también aparece registrada, aunque hoy se percibe como vulgar o anticuada.',
    '"México" mantiene la "x" por tradición histórica. En español actual, esa letra en ese nombre se pronuncia como "j", igual que en "mexicano".',
    'En español son válidas tanto la forma original "whisky" como la adaptación "güisqui". La primera es más internacional; la segunda sigue la ortografía española.',
    'La palabra "haiga" existe en el diccionario como sustantivo coloquial: se usó para describir autos grandes y ostentosos, no como forma verbal correcta de "haya".',
    'El símbolo @ se llama "arroba" en español, nombre heredado de una antigua medida de peso cuyo término viene del árabe hispánico.',
    'La "h" es muda en la mayoría de palabras del español, pero sigue siendo clave para distinguir significados, como en "hola" y "ola".',
    '"Castellano" y "español" son denominaciones válidas de la misma lengua. El uso de una u otra suele depender del país, el contexto histórico o la preferencia personal.',
    'En español, el separador decimal habitual es la coma (por ejemplo, 3,14). El punto se reserva normalmente para separar miles: 1.000.',
    'La diéresis no solo aparece en "pingüino" o "vergüenza": su función es indicar que la "u" debe pronunciarse en secuencias como "güe" y "güi".',
    'El signo # se llama "almohadilla" en español, aunque por influencia del inglés también se popularizó "hashtag" en redes sociales.',
    '"Sándwich" y "sánduche" son formas válidas en distintas zonas del mundo hispano. La variación regional forma parte natural del idioma.',
    '"Wifi" y "wifi" se consideran válidos; en textos formales suele preferirse "wifi" en minúscula, como ocurre con otras voces ya incorporadas al uso común.',
    'La Ortografía académica recomienda usar comillas angulares (« ») como primera opción en textos en español, aunque las comillas dobles (" ") también son correctas según el contexto.',
    'La palabra "ojal" y la expresión "ojalá" no tienen el mismo origen: "ojal" viene del ámbito textil, mientras que "ojalá" procede del árabe.',
    '"Latinoamérica", "Iberoamérica" e "Hispanoamérica" no son sinónimos exactos: cada término agrupa países distintos según criterios lingüísticos e históricos.',
    'El español comparte raíces con el portugués, el italiano y el francés porque todas son lenguas romances derivadas del latín vulgar.',
    '"Izquierda" proviene del vasco "ezker". Es uno de los casos más conocidos de una palabra de origen no latino incorporada al español común.',
    'En la mayoría del mundo hispano, "b" y "v" se pronuncian igual; la diferencia se mantiene sobre todo en la escritura, no en el habla cotidiana.',
    'Las letras "k" y "w" sí forman parte del abecedario español, aunque aparecen mucho menos que otras y suelen usarse en préstamos y nombres propios.',
    'En español es válido combinar signos enfáticos cuando el contexto lo pide, como en "¿¡Qué pasó!?", sobre todo en registros expresivos.',
    'Las onomatopeyas cambian según la lengua: en español el gallo hace "kikirikí", mientras que en inglés suele representarse como "cock-a-doodle-doo".',
    'Estados Unidos es uno de los países con más hispanohablantes del mundo, aunque el español no sea lengua oficial a nivel federal.',
    'Un palíndromo es una palabra o frase que se lee igual de izquierda a derecha y viceversa, como "reconocer".',
    'El español usa diminutivos con mucho valor afectivo y regional: "-ito", "-illo" o "-ico" pueden cambiar de zona en zona.',
    'También existen aumentativos productivos como "-ón" y "-azo", que pueden expresar tamaño, intensidad o matiz emocional según el contexto.',
    '"Puma" y "cóndor" llegaron al español desde lenguas andinas, reflejando el aporte indígena al vocabulario americano.',
    '"Guagua" no significa lo mismo en todo el mundo hispano: en Chile y el Caribe suele ser "autobús", mientras que en otras zonas puede significar "bebé".',
    '"Ordenador" y "computadora" son variantes regionales válidas para el mismo objeto; la elección depende del país.',
    '"Carro", "coche" y "auto" también son variantes regionales correctas para referirse a un automóvil.',
    '"Papa" y "patata" conviven en el español general: ambas son correctas, pero su uso cambia según la región.',
    '"Lentes", "gafas" y "anteojos" son tres formas válidas de nombrar el mismo objeto en distintos países.',
    '"Celular" y "móvil" son denominaciones regionales equivalentes para el teléfono portátil.',
    '"Jugo" y "zumo" son variantes regionales aceptadas; ninguna es "más correcta" que la otra fuera de su contexto de uso.',
    '"Conducir" significa guiar un vehículo, pero en muchos países se prefiere "manejar" con ese mismo sentido.',
    '"Manejar" en español también puede significar "gestionar" o "administrar", según el contexto.',
    '"Freído" y "frito" son ambos participios válidos de "freír"; "frito" es el más usado como adjetivo.',
    '"Provisto" y "proveído" son participios correctos de "proveer", con diferencias de uso según el contexto verbal o adjetival.',
    '"Impuesto" e "imponido" no funcionan igual: en el uso estándar, "impuesto" es la forma asentada como participio de "imponer".',
    'La forma "solo" sin tilde se aplica tanto al adverbio como al adjetivo en la norma actual, salvo casos excepcionales de ambigüedad real.',
    '"Guion" se escribe sin tilde en la norma académica actual, por considerarse palabra monosílaba en la pronunciación mayoritaria.',
    '"Truhan" también se escribe sin tilde por el mismo criterio normativo aplicado a otros monosílabos ortográficos.',
    '"Video" y "vídeo" son formas válidas en español; la preferencia cambia según el país.',
    '"Período" y "periodo" son igualmente correctas; ambas acentuaciones están admitidas.',
    '"Rumanía" y "Rumania" son formas válidas en español actual para el nombre del país europeo.',
    '"Sic" se usa entre corchetes en citas textuales para indicar que una forma llamativa o aparentemente incorrecta ya estaba en el original.',
    'Las Academias de la Lengua describen el uso real del español en todo el mundo hispano; no se basan solo en el español de España.',
];