export const DATOS_CURIOSOS_INICIO: string[] = [
    'Se considera más fiel al origen latino decir "extravertido" que "extrovertido", ya que proviene de extra- (hacia afuera) y vertere (girar). Aun así, "extrovertido" es hoy ampliamente aceptado y más usado.',
    'La expresión correcta es "craso error". "Craso" significa grave o evidente, mientras que "graso error" es un error por confusión fonética sin base en el significado real de la palabra.',
    'El verbo "haber", cuando indica existencia, es impersonal, por lo que siempre va en singular: se debe decir "hubo problemas" y no "hubieron problemas", incluso si el complemento está en plural.',
    '"Ojalá" proviene del árabe inshallah, que significa "si Dios quiere", reflejando la fuerte influencia árabe en el español durante la Edad Media.',
    'En contextos formales se prefiere "con base en" o "basado en", aunque "en base a" es un uso extendido en el habla cotidiana.',
    'El dequeísmo consiste en agregar innecesariamente la preposición "de", como en "pienso de que vendrá". El queísmo es el fenómeno opuesto: omitirla cuando sí corresponde, como en "estoy seguro que vendrá" en lugar de "de que".',
    '"Bizarro" originalmente significa valiente o generoso en español. Sin embargo, por influencia del inglés "bizarre", hoy también se acepta con el sentido de "extraño".',
    'La palabra "trabajo" podría estar relacionada con el latín tripalium, un instrumento de sujeción o castigo. Esta etimología sugiere una asociación histórica con el esfuerzo, la dificultad o el sufrimiento, aunque no implica que originalmente significara “tortura” en sentido literal.',
    'La palabra "chocolate" proviene del náhuatl "xocolātl" y llegó al español tras la conquista de América. Otras palabras de ese mismo origen son "tomate", "aguacate", "chile" y "cacao".',
    '"Literalmente" significa "de acuerdo con el sentido exacto de las palabras, sin interpretación figurada". Su uso como intensificador ("me morí literalmente de risa") es muy común, pero técnicamente impreciso.',
    '"Eventualmente" no significa "finalmente". En español se usa para indicar algo ocasional o circunstancial. La confusión con el inglés "eventually" ha llevado a un uso incorrecto en algunos contextos.',
    '"Chancho en piedra" proviene de "chancar en piedra", es decir, moler los ingredientes, y no tiene relación con el animal.',
    'Expresiones como "subir para arriba" o "bajar para abajo" son pleonasmos, es decir, redundancias que repiten una idea ya implícita en el verbo.',
    '"Álgido" proviene del latín algidus (“frío”), pero en el uso actual se emplea principalmente para referirse al momento más intenso o crítico de una situación, como en “el punto álgido del debate”.',
    '"Imprimido" e "impreso" son formas correctas del participio de "imprimir". "Impreso" se usa más como adjetivo, mientras que "imprimido" se emplea en tiempos compuestos.',
    'La letra "ñ" surgió en la Edad Media como una abreviación de la doble "n", y con el tiempo se consolidó como una letra propia del español.',
    '"Usted" proviene de la expresión de cortesía "vuestra merced", que con el tiempo se fue abreviando y transformando fonéticamente hasta llegar a su forma actual.',
    '"Cerca mío" es frecuente en el español de América, pero en registros formales se prefiere "cerca de mí".',
    'Formas como "dijistes", "fuistes" o "vinistes" son incorrectas, ya que los verbos en pretérito perfecto simple no llevan "s" en la segunda persona singular.',
    '"Presidente" es un sustantivo común en cuanto al género, por lo que puede usarse tanto para hombres como para mujeres, aunque "presidenta" también es válida.',
    '"Septiembre" y "setiembre" son ambas formas correctas, aunque la primera es la más utilizada.',
    '"Inflamable" y "flamable" significan lo mismo: que algo puede arder con facilidad. ¡Qué país!',
    '"Excepción" y "acepción" tienen significados distintos: la primera se refiere a algo que se aparta de la regla, y la segunda a un significado de una palabra.',
    '"Así mismo", "asimismo" y "a sí mismo" tienen significados distintos: equivalencia, adición y referencia reflexiva, respectivamente.',
    'Las mayúsculas deben llevar tilde cuando las reglas de acentuación lo exigen.',
    '"Óptimo" significa "el mejor posible dentro de una categoría", no simplemente "muy bueno".',
    '"Único" no admite grados: algo no puede ser "muy único" en sentido estricto.',
    '"El agua" utiliza artículo masculino por razones fonéticas, pero sigue siendo una palabra femenina. Por eso se dice "el agua helada", pero también "las aguas heladas".',
    'La palabra "salario" proviene del latín salarium, relacionada con la sal, y aludía a una asignación para adquirirla.',
    '"Madrugada" no tiene equivalente exacto en inglés: no existe una sola palabra en esa lengua para referirse a las horas entre medianoche y el amanecer.',
    '"Aplicar a un trabajo" es un calco del inglés y se considera poco adecuado en español formal; se prefiere "postular a un trabajo".',
    '"Pretender" significa "intentar" o "tener la intención de", no "fingir". La confusión con el inglés "pretend" ha llevado a un uso incorrecto en algunos contextos.',
    '"Constipado" en español se refiere a un resfriado leve, no a estreñimiento.',
    'El verbo “prever” se conjuga como “ver”, por lo que la forma correcta es “previó” y no “preveyó”.',
    '"Sendos" no significa "grandes", sino "uno para cada uno". Ejemplo: "recibieron sendos premios" quiere decir que cada uno recibió un premio. La forma singular "sendo" no forma parte del uso estándar.',
    '"Enervar" significa debilitar o quitar energía, no "poner nervioso", aunque este último uso es frecuente.',
    '"Demás" y "de más" no significan lo mismo: el primero se refiere a otros, el segundo a exceso.',
    '"Sino" y "si no" cumplen funciones distintas: oposición y condición, respectivamente.',
    '"Aparte" y "a parte" no son equivalentes: el primero significa "además" o "separado", el segundo implica "una parte de".',
    '"Sobre todo" significa "principalmente", mientras que "sobretodo" es una prenda de vestir.',
    '"Vaya", "valla" y "baya" tienen significados distintos: forma verbal o interjección, cerca, y fruto, respectivamente.',
    '"Haya", "halla" y "allá" se diferencian en significado: verbo haber o árbol, verbo hallar, y lugar.',
    'El adverbio "medio" es invariable cuando equivale a "un poco": se dice "medio cansada", no "media cansada".',
    '"Quien" y "quienes" llevan tilde ("quién", "quiénes") solo en interrogativas o exclamativas, directas o indirectas.',
    '"Por qué", "porque", "porqué" y "por que" cumplen funciones distintas: interrogativo, causal, sustantivo y combinación preposición + relativo.',
    '"A ver" (ver) y "haber" (verbo auxiliar) no son intercambiables: "a ver qué pasa" vs "debe haber algo".',
    '"Hecho" (del verbo hacer) y "echo" (del verbo echar) se distinguen por su origen y significado, aunque suenen igual.',
    '"Hay", "ahí" y "ay" tienen significados distintos: existencia, lugar e interjección, respectivamente.',
    '"Aun" y "aún" no siempre son intercambiables: "aún" equivale a "todavía", mientras que "aun" puede significar "incluso".',
    'Las palabras extranjeras adaptadas al español deben seguir sus reglas ortográficas: "fútbol", "líder", "récord".',
    '"Currículum" tiene varias formas de plural aceptadas: "currículums" y "currícula".',
    'Los días de la semana y los meses se escriben con minúscula en español, por ejemplo "lunes" y "enero".',
    'Las siglas no llevan puntos ni plural con "s": se escribe "las ONG", no "las ONGs".',
    'Las palabras terminadas en -mente conservan la tilde del adjetivo original: "rápidamente", "fácilmente".',
    '"Le" puede funcionar como complemento indirecto incluso en plural ("le dije a ellos"), fenómeno conocido como leísmo de cortesía en algunos contextos.',
    '"Hubiera" y "hubiese" son formas equivalentes del pretérito imperfecto del subjuntivo.',
    '"Donde", "cuando" y "como" llevan tilde ("dónde", "cuándo", "cómo") en preguntas o énfasis.',
    'El verbo "caber" en pretérito es irregular: "cupe", "cupiste", "cupo".',
    '"Habían dicho" es correcto cuando "haber" es auxiliar, pero "habían personas" es incorrecto por ser impersonal.',
    '"Peor" y "mejor" son comparativos irregulares y no se combinan con "más": no se dice "más mejor".',
    '"Muy" modifica adjetivos o adverbios ("muy alto"), mientras que "mucho" modifica sustantivos o verbos ("mucho trabajo", "trabaja mucho").',
    '"Súper" como prefijo se escribe junto: "supermercado", pero separado cuando es adverbio coloquial: "súper bueno".',
    '"Ambos dos" es redundante, ya que "ambos" ya implica dualidad.',
    '"Más" lleva tilde cuando indica cantidad o comparación ("quiero más", "es más alto"), mientras que "mas" sin tilde es una conjunción equivalente a "pero", hoy poco usada ("quiso ir, mas no pudo").',
    '"Asumir" significa aceptar o hacerse cargo de algo ("asumió el cargo"), no simplemente "suponer". Aunque este último uso es frecuente por influencia del inglés "assume", en contextos formales se prefiere "suponer".',
    'El verbo "abolir" es defectivo: no se usa en todas sus formas, por lo que expresiones como "yo abolo" o "tú aboles" no se consideran correctas en el uso estándar.',
    '"Recién" en varios países de América se usa como marcador de pasado inmediato ("recién llegué"), mientras que en español estándar se prefiere "acabo de llegar".',
    '"Nomás" es una contracción de "no más", válida en el uso coloquial; en registros formales se prefiere escribirlo separado.',
    'La doble negación es correcta en español: "no vi a nadie" es gramatical y refuerza la negación.',
    '"Cancha" proviene del quechua "kancha", que significaba espacio abierto o recinto. Es uno de los muchos aportes de las lenguas indígenas al español de América.',
    'El español tiene más de 480 millones de hablantes nativos, lo que lo convierte en la segunda lengua con más hablantes maternos del mundo, por delante del inglés.',
    '"Cuyo" indica posesión y concuerda en género y número con lo poseído, no con el poseedor. Es una palabra que casi ha desaparecido del habla cotidiana, pero que se mantiene en la escritura formal.',
    '"Acertar" no proviene de "cierto" (verdadero), sino del latín "ad-certare" (dirigirse hacia un blanco). Por eso "acertar" implica dar en el objetivo, no solo tener razón.',
    'El uso de "vos" como pronombre de segunda persona singular, frecuente en Argentina, Uruguay y parte de Centroamérica, es un arcaísmo medieval que desapareció del español europeo pero sobrevivió en América.',
    'Hasta 2010, "ch" y "ll" se consideraban letras del abecedario. Hoy se clasifican como dígrafos, aunque siguen sonando como unidades en muchos contextos.',
    'La Real Academia registra formas como "almóndiga" y "toballa" como variantes populares o vulgares: existen en el diccionario, pero no se recomiendan en la norma culta.',
    '"Murciégalo" no es una invención moderna: es una variante histórica de "murciélago" que también aparece registrada, aunque hoy se percibe como vulgar o anticuada.',
    '"México" mantiene la "x" por tradición histórica. En español actual, esa letra en ese nombre se pronuncia como "j", igual que en "mexicano".',
    'En español son válidas tanto la forma original "whisky" como la adaptación "güisqui". La primera es más internacional; la segunda sigue la ortografía española.',
    'La palabra "haiga" existe en el diccionario como sustantivo coloquial: se usó para describir autos grandes y ostentosos, no como forma verbal correcta de "haya".',
    'El símbolo @ se llama "arroba" en español, nombre heredado de una antigua medida de peso cuyo término viene del árabe hispánico.',
    'La "h" es muda en la mayoría de palabras del español, pero sigue siendo clave para distinguir significados, como en "hola" y "ola".',
    '"Castellano" y "español" son denominaciones válidas de la misma lengua. El uso de una u otra suele depender del país, el contexto histórico o la preferencia personal.',
    'En español, el separador decimal habitual es la coma (por ejemplo, 3,14). El punto se reserva normalmente para separar miles: 1.000.',
    'La diéresis no solo aparece en "pingüino" o "vergüenza": su función es indicar que la "u" debe pronunciarse en secuencias como "güe" y "güi".',
    'El signo # se llama "almohadilla" en español, aunque por influencia del inglés también se popularizó "hashtag" en redes sociales.',
    '"Sándwich" y "sánduche" son formas válidas en distintas zonas del mundo hispano. La variación regional forma parte natural del idioma.',
    '"Wi-Fi" y "wifi" se consideran válidos, aunque en textos formales suele preferirse "wifi" en minúscula.',
    'La Ortografía académica recomienda usar comillas angulares (« ») como primera opción en textos en español, aunque las comillas dobles (" ") también son correctas según el contexto.',
    '"Latinoamérica", "Iberoamérica" e "Hispanoamérica" no son sinónimos exactos: cada término agrupa países distintos según criterios lingüísticos e históricos.',
    'El español comparte raíces con el portugués, el italiano y el francés porque todas son lenguas romances derivadas del latín vulgar.',
    '"Izquierda" proviene del vasco "ezker". Es uno de los casos más conocidos de una palabra de origen no latino incorporada al español común.',
    'En la mayoría del mundo hispano, "b" y "v" se pronuncian igual; la diferencia se mantiene sobre todo en la escritura, no en el habla cotidiana.',
    'Las letras "k" y "w" sí forman parte del abecedario español, aunque aparecen mucho menos que otras y suelen usarse en préstamos y nombres propios.',
    'En español es válido combinar signos enfáticos cuando el contexto lo pide, como en "¿¡Qué pasó!?", sobre todo en registros expresivos.',
    'Las onomatopeyas cambian según la lengua: en español el gallo hace "kikirikí", mientras que en inglés suele representarse como "cock-a-doodle-doo".',
    'Estados Unidos es uno de los países con más hispanohablantes del mundo, aunque el español no sea lengua oficial a nivel federal.',
    'Un palíndromo es una palabra o frase que se lee igual de izquierda a derecha y viceversa, como "reconocer".',
    'El español usa diminutivos con mucho valor afectivo y regional: "-ito", "-illo" o "-ico" pueden cambiar de zona en zona.',
    '"Puma" y "cóndor" llegaron al español desde lenguas andinas, reflejando el aporte indígena al vocabulario americano.',
    '"Guagua" no significa lo mismo en todo el mundo hispano: en Chile suele significar "bebé", mientras que en el Caribe y Canarias suele significar "autobús".',
    '"Papa" y "patata" conviven en el español general: ambas son correctas, pero su uso cambia según la región.',
    '"Jugo" y "zumo" son variantes regionales aceptadas; ninguna es "más correcta" que la otra fuera de su contexto de uso.',
    '"Freído" y "frito" son ambos participios válidos de "freír"; "frito" es el más usado como adjetivo.',
    '"Provisto" y "proveído" son participios correctos de "proveer", con diferencias de uso según el contexto verbal o adjetival.',
    '"Impuesto" e "imponido" no funcionan igual: en el uso estándar, "impuesto" es la forma asentada como participio de "imponer".',
    'La forma "solo" sin tilde se aplica tanto al adverbio como al adjetivo en la norma actual, salvo casos excepcionales de ambigüedad real.',
    'Palabras como "guion" o "truhan" se escriben sin tilde en la norma académica actual, por considerarse palabras monosílabas en la pronunciación mayoritaria.',
    '"Video" y "vídeo" son formas válidas en español; la preferencia cambia según el país.',
    '"Período" y "periodo" son igualmente correctas; ambas acentuaciones están admitidas.',
    '"Rumanía" y "Rumania" son formas válidas en español actual para el nombre del país europeo.',
    '"Sic" se usa entre corchetes en citas textuales para indicar que una forma llamativa o aparentemente incorrecta ya estaba en el original.',
    'Las Academias de la Lengua describen el uso real del español en todo el mundo hispano; no se basan solo en el español de España.',
    '"Aguacate" proviene del náhuatl "āhuacatl", que también significaba "testículo", probablemente por la forma de la fruta. Esta etimología refleja cómo muchas palabras del español tienen raíces indígenas americanas. En países como Chile, se le conoce como "palta".',
    '"Chicle" proviene del náhuatl "tzictli", que se refería a la resina de ciertos árboles utilizada para mascar. La palabra llegó al español tras la conquista de América y se ha mantenido en el uso cotidiano.',
    '"Tío" y "tía" como formas de tratamiento entre amigos son exclusivas del español de España. En el resto del mundo hispano pueden sonar extrañas o incluso confusas, ya que conservan el significado familiar.',
    '"Gringo" tiene origen incierto: hay quienes lo relacionan con "griego" (como sinónimo de "lengua incomprensible"), aunque ninguna etimología está confirmada del todo. Lo interesante es que su carga negativa varía mucho según el país.',
    '"Ceviche", "cebiche", "sebiche" y "seviche" son todas formas aceptadas por la RAE. La variación ortográfica refleja la diversidad regional del español antes que un error.',
    '"Anteayer" es una palabra que existe en español pero no tiene equivalente simple en inglés ("the day before yesterday" requiere tres palabras). Lo mismo ocurre con "anteanoche".',
    'El español es la única lengua del mundo que usa signos de apertura de interrogación y exclamación (¿ y ¡). Fueron introducidos por la Real Academia en 1754 para facilitar la lectura de textos largos.',
    '"Fulano", "mengano", "zutano" y "perengano" son palabras de origen árabe usadas para referirse a personas indeterminadas. "Fulano" viene del árabe "fulān", que significa exactamente eso: alguien sin nombre específico.',
    'La "b" y la "v" nunca se diferenciaron fonéticamente en latín vulgar, el origen del español. Por eso su distinción escrita es histórica, no fonética, y la confusión entre ambas es completamente natural.',
    'La expresión "en absoluto" significa "de ninguna manera", es decir, una negación total. Sin embargo, por influencia del inglés "absolutely", muchos la usan erróneamente como sinónimo de "completamente" o "por supuesto".',
    '"Trasnochar" es un ejemplo de concepto con nombre propio en español: significa quedarse despierto hasta muy tarde o toda la noche. En inglés no existe un verbo único para esto.',
    '"Soler" es un verbo defectivo que expresa hábito o frecuencia ("suelo desayunar temprano"), pero no tiene todas sus formas verbales: no se usa en futuro ni en condicional. Es decir, no puedes decir "soleré" ni "solería" en el uso estándar.',
    'El verbo "tutear" describe el acto de hablar de "tú" a alguien. Es uno de los pocos casos en que el pronombre personal da origen a un verbo: también existe "vosear" para el uso del "vos".',
    'En español existe el "laísmo": usar "la" como complemento indirecto femenino ("la dije que viniera"). Aunque muy extendido en algunas zonas de España, no es la norma académica recomendada.',
];