export const DATOS_CURIOSOS_INICIO: string[] = [
  'Se considera más fiel al origen latino decir "extravertido" que "extrovertido", ya que proviene de extra- (hacia afuera) y vertere (girar). Aun así, "extrovertido" es hoy ampliamente aceptado y más usado.',
  'La expresión correcta es "craso error". "Craso" significa grave o evidente, mientras que "graso error" es un error por confusión fonética sin base en el significado real de la palabra.',
  'El verbo "haber" cuando indica existencia es impersonal, por lo que siempre va en singular: se debe decir "hubo problemas" y no "hubieron problemas", incluso si el complemento está en plural.',
  '"Ojalá" proviene del árabe inshallah, que significa "si Dios quiere", reflejando la fuerte influencia árabe en el español durante la Edad Media.',
  'En contextos formales se recomienda "con base en" o "basado en", ya que "en base a" es un uso extendido pero menos tradicional en la norma culta.',
  'El dequeísmo consiste en agregar innecesariamente la preposición "de", como en "pienso de que vendrá". El queísmo es el fenómeno opuesto: omitirla cuando sí corresponde, como en "estoy seguro que vendrá" en lugar de "de que".',
  '"Bizarro" originalmente significa valiente o generoso en español. Sin embargo, por influencia del inglés "bizarre", hoy también se acepta con el sentido de "extraño", aunque este uso es relativamente reciente.',
  'La palabra "trabajo" podría estar relacionada con el latín tripalium, un instrumento de sujeción o castigo. Esta etimología sugiere una asociación histórica con el esfuerzo o la dificultad, más que con tortura literal.',
  '"Solo" no lleva tilde según las normas actuales, salvo en casos poco frecuentes donde su ausencia pueda generar ambigüedad real en la interpretación de la frase.',
  '"Literalmente" significa "de manera exacta, sin exageración". Su uso como intensificador ("me morí literalmente de risa") es muy común, pero técnicamente impreciso.',
  '"Eventualmente" no significa "finalmente". En español se usa para indicar algo ocasional o circunstancial, mientras que el uso como "a la larga" proviene del inglés eventually.',
  '"A ver" y "haber" suenan igual, pero cumplen funciones distintas: "a ver" introduce una expectativa o petición ("vamos a ver"), mientras que "haber" es un verbo auxiliar o sustantivo.',
  '"Porque", "por qué", "por que" y "porqué" tienen usos distintos: conjunción causal, interrogativo, combinación preposición+relativo y sustantivo, respectivamente.',
  '"Murciélago" es una de las pocas palabras en español que contiene las cinco vocales distintas, lo que la hace popular como curiosidad lingüística.',
  'Muchas palabras del español que comienzan con "al-", como "almohada", "alcalde" o "aceituna", provienen del árabe, ya que ese prefijo corresponde al artículo definido en esa lengua.',
  '"Chancho en piedra" no hace referencia al animal, sino que proviene de "chancar en piedra", es decir, moler los ingredientes en un mortero o superficie de piedra.',
  'Expresiones como "subir para arriba" o "bajar para abajo" son pleonasmos: redundancias que repiten una idea ya implícita en el verbo.',
  '"Álgido" no significa "muy frío", sino "el momento más intenso o crítico de una situación", como en "el punto álgido del debate".',
  '"Imprimido" e "impreso" son formas correctas del participio de "imprimir". "Impreso" se usa más como adjetivo ("documento impreso"), mientras que "imprimido" se emplea en tiempos compuestos.',
  'La letra "ñ" surgió en la Edad Media como una abreviación de la doble "n", y con el tiempo se consolidó como una letra propia del español.',
  '"Cerca mío" es frecuente en el español de América, pero en registros formales se prefiere "cerca de mí", ya que los pronombres posesivos no sustituyen correctamente esa estructura.',
  'Formas como "dijistes", "fuistes" o "vinistes" son incorrectas, ya que los verbos en pretérito perfecto simple no llevan "s" en la segunda persona singular.',
  '"Más mejor" o "más peor" son redundancias, porque "mejor" y "peor" ya expresan comparación por sí mismos.',
  '"Presidente" es un sustantivo común en cuanto al género, por lo que puede usarse tanto para hombres como para mujeres. No obstante, "presidenta" también es una forma válida y extendida.',
  '"Septiembre" y "setiembre" son ambas formas correctas, aunque la primera es la más utilizada en la mayoría de los países.',
  '"Aún" lleva tilde cuando equivale a "todavía" ("aún no llega"), pero no la lleva cuando significa "incluso" ("aun los expertos se equivocan").',
  '"Hay", "ahí" y "ay" son homófonos con significados distintos: existencia, lugar y exclamación, respectivamente.',
  '"De repente" significa "de manera súbita o inesperada", no "quizás", aunque ese uso es frecuente en algunos países.',
  '"Inflamable" y "flamable" significan lo mismo: que algo puede arder con facilidad. La forma "inflamable" es la más común.',
  '"Ambos dos" es redundante, ya que "ambos" ya significa "los dos".',
  '"Preveer" es incorrecto; la forma correcta es "prever", formada a partir del verbo "ver".',
  '"Accesible" se escribe con una sola "c" en el centro, aunque por analogía con otras palabras muchos escriben erróneamente "accesible".',
  '"Excepción" y "acepción" tienen significados distintos: la primera se refiere a algo que se aparta de la regla, y la segunda a un significado particular de una palabra.',
  '"Gratis" es un adverbio invariable, por lo que no tiene plural: decir "gratises" es incorrecto.',
  '"Así mismo", "asimismo" y "a sí mismo" tienen significados distintos: equivalencia, además, y referencia reflexiva, respectivamente.',
  'Las letras mayúsculas deben llevar tilde cuando las reglas de acentuación lo exigen, aunque muchas veces se omita en la práctica.',
  '"Idiosincrasia" es una palabra que suele escribirse mal; su forma correcta incluye una "s" después de la "o" y no lleva tilde.',
  '"Había muchas personas" es correcto, mientras que "habían muchas personas" es incorrecto, ya que el verbo "haber" en ese uso es impersonal.',
  '"En serio" es la forma correcta para expresar seriedad; "enserio" no es una forma reconocida en este contexto.',
  '"Óptimo" significa "el mejor posible dentro de una categoría", no simplemente "muy bueno".',
  '"Único" no admite grados: algo no puede ser "muy único", aunque ese uso aparezca en el habla informal.',
  '"El agua" utiliza el artículo masculino por razones fonéticas, pero sigue siendo una palabra femenina, como se ve en "el agua fría".',
  'La palabra "salario" proviene del latín salarium, relacionada con la sal, un recurso valioso en la antigüedad. Se cree que hacía referencia a una asignación para adquirirla, no a un pago directo en sal.',
  '"Aplicar a un trabajo" es un calco del inglés y se considera poco adecuado en español formal. Se recomienda "postular a un trabajo" o "presentarse a un trabajo".',
  '"Realizar" no significa "darse cuenta". En español significa "llevar a cabo", mientras que el uso como "notar" proviene del inglés realize.',
  '"Actualmente" significa "en el presente", no "en realidad". Este último uso proviene del inglés actually.',
  '"Asistir" significa "acudir a un lugar", no "ayudar", aunque este último sentido se deba a la influencia del inglés assist.',
  '"Argumento" en español se refiere a la idea o trama de algo, y no necesariamente a una discusión, como ocurre en inglés con argument.',
  '"Pretender" en español significa "intentar" o "tener la intención de", no "fingir", que es el sentido del inglés pretend.',
  '"Librería" es un lugar donde se venden libros, no una biblioteca, aunque esta confusión proviene del inglés library.',
  '"Carpeta" en español es un objeto para guardar documentos, mientras que "carpet" en inglés significa alfombra.',
  '"Constipado" en español se refiere a un resfriado leve, mientras que en inglés constipated significa estreñido.',
  '"Decepción" significa desilusión o desencanto, no engaño, como podría sugerir el inglés deception.',
  '"Embarazada" significa estar en gestación, y no avergonzada, a pesar de su parecido con el inglés embarrassed.',
  '"Fabricar" significa producir o elaborar algo, no "tela", que es el significado de fabric en inglés.',
  '"Colegio" en muchos países hispanohablantes se refiere a una institución escolar previa a la universidad, no a educación superior como en inglés college.'
];
